name: flutter_goal_savings
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_spinkit: '^2.1.0'
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          style: normal
          weight: 700
